name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --no-save

      - name: Run tests with coverage
        run: bun test --coverage | tee coverage.txt

      - name: Enforce coverage threshold >= 90%
        shell: bash
        run: |
          set -euo pipefail
          LINE=$(grep '^All files' coverage.txt || true)
          if [ -z "$LINE" ]; then
            echo "Coverage summary not found" >&2
            cat coverage.txt || true
            exit 1
          fi
          FUNCS=$(echo "$LINE" | awk -F '|' '{gsub(/ /, "", $2); print $2}')
          LINES=$(echo "$LINE" | awk -F '|' '{gsub(/ /, "", $3); print $3}')
          echo "Coverage summary: Funcs=$FUNCS Lines=$LINES"
          FUNCS_INT=${FUNCS%.*}
          LINES_INT=${LINES%.*}
          if [ "${FUNCS_INT}" -lt 90 ] || [ "${LINES_INT}" -lt 90 ]; then
            echo "Coverage below threshold 90%" >&2
            exit 1
          fi

