name: Release (JSR Publish)

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --no-save

      - name: Build library (CSR + SSR)
        run: bun run build

      - name: Run tests
        run: bun test --coverage | cat

      - name: Publish to JSR (allow slow types)
        env:
          JSR_TOKEN: ${{ secrets.JSR_TOKEN }}
        run: bunx jsr publish --allow-slow-types

